version: "3.8"

services:
  # 🧠 MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  # 💡 openHAB (ใช้ image สำเร็จรูปที่มี Java แล้ว)
  openhab:
    image: openhab/openhab:4.2.0
    container_name: openhab
    restart: unless-stopped
    network_mode: host
    environment:
      - USER_ID=9001
      - GROUP_ID=9001
      - TZ=Asia/Bangkok
    volumes:
      - ./openhab_addons:/openhab/addons
      - ./openhab_conf:/openhab/conf
      - ./openhab_user:/openhab/userdata

  # 💾 MongoDB (ฐานข้อมูล)
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    restart: always
